// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: system_data.proto

#ifndef PROTOBUF_INCLUDED_system_5fdata_2eproto
#define PROTOBUF_INCLUDED_system_5fdata_2eproto

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3006001
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3006001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#define PROTOBUF_INTERNAL_EXPORT_protobuf_system_5fdata_2eproto 

namespace protobuf_system_5fdata_2eproto {
// Internal implementation detail -- do not use these members.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[5];
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static const ::google::protobuf::uint32 offsets[];
};
void AddDescriptors();
}  // namespace protobuf_system_5fdata_2eproto
class CPU;
class CPUDefaultTypeInternal;
extern CPUDefaultTypeInternal _CPU_default_instance_;
class Disk;
class DiskDefaultTypeInternal;
extern DiskDefaultTypeInternal _Disk_default_instance_;
class Memory;
class MemoryDefaultTypeInternal;
extern MemoryDefaultTypeInternal _Memory_default_instance_;
class SysProcess;
class SysProcessDefaultTypeInternal;
extern SysProcessDefaultTypeInternal _SysProcess_default_instance_;
class SystemData;
class SystemDataDefaultTypeInternal;
extern SystemDataDefaultTypeInternal _SystemData_default_instance_;
namespace google {
namespace protobuf {
template<> ::CPU* Arena::CreateMaybeMessage<::CPU>(Arena*);
template<> ::Disk* Arena::CreateMaybeMessage<::Disk>(Arena*);
template<> ::Memory* Arena::CreateMaybeMessage<::Memory>(Arena*);
template<> ::SysProcess* Arena::CreateMaybeMessage<::SysProcess>(Arena*);
template<> ::SystemData* Arena::CreateMaybeMessage<::SystemData>(Arena*);
}  // namespace protobuf
}  // namespace google

// ===================================================================

class CPU : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:CPU) */ {
 public:
  CPU();
  virtual ~CPU();

  CPU(const CPU& from);

  inline CPU& operator=(const CPU& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  CPU(CPU&& from) noexcept
    : CPU() {
    *this = ::std::move(from);
  }

  inline CPU& operator=(CPU&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const CPU& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const CPU* internal_default_instance() {
    return reinterpret_cast<const CPU*>(
               &_CPU_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  void Swap(CPU* other);
  friend void swap(CPU& a, CPU& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline CPU* New() const final {
    return CreateMaybeMessage<CPU>(NULL);
  }

  CPU* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<CPU>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const CPU& from);
  void MergeFrom(const CPU& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(CPU* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional string name = 1;
  bool has_name() const;
  void clear_name();
  static const int kNameFieldNumber = 1;
  const ::std::string& name() const;
  void set_name(const ::std::string& value);
  #if LANG_CXX11
  void set_name(::std::string&& value);
  #endif
  void set_name(const char* value);
  void set_name(const char* value, size_t size);
  ::std::string* mutable_name();
  ::std::string* release_name();
  void set_allocated_name(::std::string* name);

  // optional float usage = 2;
  bool has_usage() const;
  void clear_usage();
  static const int kUsageFieldNumber = 2;
  float usage() const;
  void set_usage(float value);

  // optional float user_usage = 3;
  bool has_user_usage() const;
  void clear_user_usage();
  static const int kUserUsageFieldNumber = 3;
  float user_usage() const;
  void set_user_usage(float value);

  // optional float system_usage = 4;
  bool has_system_usage() const;
  void clear_system_usage();
  static const int kSystemUsageFieldNumber = 4;
  float system_usage() const;
  void set_system_usage(float value);

  // optional float irq_usage = 5;
  bool has_irq_usage() const;
  void clear_irq_usage();
  static const int kIrqUsageFieldNumber = 5;
  float irq_usage() const;
  void set_irq_usage(float value);

  // optional float softirq_usage = 6;
  bool has_softirq_usage() const;
  void clear_softirq_usage();
  static const int kSoftirqUsageFieldNumber = 6;
  float softirq_usage() const;
  void set_softirq_usage(float value);

  // optional int32 running_time = 7;
  bool has_running_time() const;
  void clear_running_time();
  static const int kRunningTimeFieldNumber = 7;
  ::google::protobuf::int32 running_time() const;
  void set_running_time(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:CPU)
 private:
  void set_has_name();
  void clear_has_name();
  void set_has_usage();
  void clear_has_usage();
  void set_has_user_usage();
  void clear_has_user_usage();
  void set_has_system_usage();
  void clear_has_system_usage();
  void set_has_irq_usage();
  void clear_has_irq_usage();
  void set_has_softirq_usage();
  void clear_has_softirq_usage();
  void set_has_running_time();
  void clear_has_running_time();

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  ::google::protobuf::internal::ArenaStringPtr name_;
  float usage_;
  float user_usage_;
  float system_usage_;
  float irq_usage_;
  float softirq_usage_;
  ::google::protobuf::int32 running_time_;
  friend struct ::protobuf_system_5fdata_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class Memory : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:Memory) */ {
 public:
  Memory();
  virtual ~Memory();

  Memory(const Memory& from);

  inline Memory& operator=(const Memory& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  Memory(Memory&& from) noexcept
    : Memory() {
    *this = ::std::move(from);
  }

  inline Memory& operator=(Memory&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Memory& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const Memory* internal_default_instance() {
    return reinterpret_cast<const Memory*>(
               &_Memory_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  void Swap(Memory* other);
  friend void swap(Memory& a, Memory& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline Memory* New() const final {
    return CreateMaybeMessage<Memory>(NULL);
  }

  Memory* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<Memory>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const Memory& from);
  void MergeFrom(const Memory& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Memory* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional string name = 1;
  bool has_name() const;
  void clear_name();
  static const int kNameFieldNumber = 1;
  const ::std::string& name() const;
  void set_name(const ::std::string& value);
  #if LANG_CXX11
  void set_name(::std::string&& value);
  #endif
  void set_name(const char* value);
  void set_name(const char* value, size_t size);
  ::std::string* mutable_name();
  ::std::string* release_name();
  void set_allocated_name(::std::string* name);

  // optional float total = 2;
  bool has_total() const;
  void clear_total();
  static const int kTotalFieldNumber = 2;
  float total() const;
  void set_total(float value);

  // optional float used = 3;
  bool has_used() const;
  void clear_used();
  static const int kUsedFieldNumber = 3;
  float used() const;
  void set_used(float value);

  // optional float free = 4;
  bool has_free() const;
  void clear_free();
  static const int kFreeFieldNumber = 4;
  float free() const;
  void set_free(float value);

  // optional float shared = 5;
  bool has_shared() const;
  void clear_shared();
  static const int kSharedFieldNumber = 5;
  float shared() const;
  void set_shared(float value);

  // optional float buffer_and_cached = 6;
  bool has_buffer_and_cached() const;
  void clear_buffer_and_cached();
  static const int kBufferAndCachedFieldNumber = 6;
  float buffer_and_cached() const;
  void set_buffer_and_cached(float value);

  // @@protoc_insertion_point(class_scope:Memory)
 private:
  void set_has_name();
  void clear_has_name();
  void set_has_total();
  void clear_has_total();
  void set_has_used();
  void clear_has_used();
  void set_has_free();
  void clear_has_free();
  void set_has_shared();
  void clear_has_shared();
  void set_has_buffer_and_cached();
  void clear_has_buffer_and_cached();

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  ::google::protobuf::internal::ArenaStringPtr name_;
  float total_;
  float used_;
  float free_;
  float shared_;
  float buffer_and_cached_;
  friend struct ::protobuf_system_5fdata_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class Disk : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:Disk) */ {
 public:
  Disk();
  virtual ~Disk();

  Disk(const Disk& from);

  inline Disk& operator=(const Disk& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  Disk(Disk&& from) noexcept
    : Disk() {
    *this = ::std::move(from);
  }

  inline Disk& operator=(Disk&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Disk& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const Disk* internal_default_instance() {
    return reinterpret_cast<const Disk*>(
               &_Disk_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  void Swap(Disk* other);
  friend void swap(Disk& a, Disk& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline Disk* New() const final {
    return CreateMaybeMessage<Disk>(NULL);
  }

  Disk* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<Disk>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const Disk& from);
  void MergeFrom(const Disk& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Disk* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional string file_system = 1;
  bool has_file_system() const;
  void clear_file_system();
  static const int kFileSystemFieldNumber = 1;
  const ::std::string& file_system() const;
  void set_file_system(const ::std::string& value);
  #if LANG_CXX11
  void set_file_system(::std::string&& value);
  #endif
  void set_file_system(const char* value);
  void set_file_system(const char* value, size_t size);
  ::std::string* mutable_file_system();
  ::std::string* release_file_system();
  void set_allocated_file_system(::std::string* file_system);

  // optional string mount = 4;
  bool has_mount() const;
  void clear_mount();
  static const int kMountFieldNumber = 4;
  const ::std::string& mount() const;
  void set_mount(const ::std::string& value);
  #if LANG_CXX11
  void set_mount(::std::string&& value);
  #endif
  void set_mount(const char* value);
  void set_mount(const char* value, size_t size);
  ::std::string* mutable_mount();
  ::std::string* release_mount();
  void set_allocated_mount(::std::string* mount);

  // optional float total = 2;
  bool has_total() const;
  void clear_total();
  static const int kTotalFieldNumber = 2;
  float total() const;
  void set_total(float value);

  // optional float usage = 3;
  bool has_usage() const;
  void clear_usage();
  static const int kUsageFieldNumber = 3;
  float usage() const;
  void set_usage(float value);

  // @@protoc_insertion_point(class_scope:Disk)
 private:
  void set_has_file_system();
  void clear_has_file_system();
  void set_has_total();
  void clear_has_total();
  void set_has_usage();
  void clear_has_usage();
  void set_has_mount();
  void clear_has_mount();

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  ::google::protobuf::internal::ArenaStringPtr file_system_;
  ::google::protobuf::internal::ArenaStringPtr mount_;
  float total_;
  float usage_;
  friend struct ::protobuf_system_5fdata_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class SysProcess : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:SysProcess) */ {
 public:
  SysProcess();
  virtual ~SysProcess();

  SysProcess(const SysProcess& from);

  inline SysProcess& operator=(const SysProcess& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  SysProcess(SysProcess&& from) noexcept
    : SysProcess() {
    *this = ::std::move(from);
  }

  inline SysProcess& operator=(SysProcess&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const SysProcess& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const SysProcess* internal_default_instance() {
    return reinterpret_cast<const SysProcess*>(
               &_SysProcess_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    3;

  void Swap(SysProcess* other);
  friend void swap(SysProcess& a, SysProcess& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline SysProcess* New() const final {
    return CreateMaybeMessage<SysProcess>(NULL);
  }

  SysProcess* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<SysProcess>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const SysProcess& from);
  void MergeFrom(const SysProcess& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(SysProcess* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional string name = 1;
  bool has_name() const;
  void clear_name();
  static const int kNameFieldNumber = 1;
  const ::std::string& name() const;
  void set_name(const ::std::string& value);
  #if LANG_CXX11
  void set_name(::std::string&& value);
  #endif
  void set_name(const char* value);
  void set_name(const char* value, size_t size);
  ::std::string* mutable_name();
  ::std::string* release_name();
  void set_allocated_name(::std::string* name);

  // optional int32 total = 2;
  bool has_total() const;
  void clear_total();
  static const int kTotalFieldNumber = 2;
  ::google::protobuf::int32 total() const;
  void set_total(::google::protobuf::int32 value);

  // optional int32 running = 3;
  bool has_running() const;
  void clear_running();
  static const int kRunningFieldNumber = 3;
  ::google::protobuf::int32 running() const;
  void set_running(::google::protobuf::int32 value);

  // optional int32 sleeping = 4;
  bool has_sleeping() const;
  void clear_sleeping();
  static const int kSleepingFieldNumber = 4;
  ::google::protobuf::int32 sleeping() const;
  void set_sleeping(::google::protobuf::int32 value);

  // optional int32 stopped = 5;
  bool has_stopped() const;
  void clear_stopped();
  static const int kStoppedFieldNumber = 5;
  ::google::protobuf::int32 stopped() const;
  void set_stopped(::google::protobuf::int32 value);

  // optional int32 zombie = 6;
  bool has_zombie() const;
  void clear_zombie();
  static const int kZombieFieldNumber = 6;
  ::google::protobuf::int32 zombie() const;
  void set_zombie(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:SysProcess)
 private:
  void set_has_name();
  void clear_has_name();
  void set_has_total();
  void clear_has_total();
  void set_has_running();
  void clear_has_running();
  void set_has_sleeping();
  void clear_has_sleeping();
  void set_has_stopped();
  void clear_has_stopped();
  void set_has_zombie();
  void clear_has_zombie();

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  ::google::protobuf::internal::ArenaStringPtr name_;
  ::google::protobuf::int32 total_;
  ::google::protobuf::int32 running_;
  ::google::protobuf::int32 sleeping_;
  ::google::protobuf::int32 stopped_;
  ::google::protobuf::int32 zombie_;
  friend struct ::protobuf_system_5fdata_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class SystemData : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:SystemData) */ {
 public:
  SystemData();
  virtual ~SystemData();

  SystemData(const SystemData& from);

  inline SystemData& operator=(const SystemData& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  SystemData(SystemData&& from) noexcept
    : SystemData() {
    *this = ::std::move(from);
  }

  inline SystemData& operator=(SystemData&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const SystemData& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const SystemData* internal_default_instance() {
    return reinterpret_cast<const SystemData*>(
               &_SystemData_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    4;

  void Swap(SystemData* other);
  friend void swap(SystemData& a, SystemData& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline SystemData* New() const final {
    return CreateMaybeMessage<SystemData>(NULL);
  }

  SystemData* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<SystemData>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const SystemData& from);
  void MergeFrom(const SystemData& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(SystemData* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated .CPU cpus = 2;
  int cpus_size() const;
  void clear_cpus();
  static const int kCpusFieldNumber = 2;
  ::CPU* mutable_cpus(int index);
  ::google::protobuf::RepeatedPtrField< ::CPU >*
      mutable_cpus();
  const ::CPU& cpus(int index) const;
  ::CPU* add_cpus();
  const ::google::protobuf::RepeatedPtrField< ::CPU >&
      cpus() const;

  // repeated .Disk disks = 5;
  int disks_size() const;
  void clear_disks();
  static const int kDisksFieldNumber = 5;
  ::Disk* mutable_disks(int index);
  ::google::protobuf::RepeatedPtrField< ::Disk >*
      mutable_disks();
  const ::Disk& disks(int index) const;
  ::Disk* add_disks();
  const ::google::protobuf::RepeatedPtrField< ::Disk >&
      disks() const;

  // optional .CPU sys_cpu = 1;
  bool has_sys_cpu() const;
  void clear_sys_cpu();
  static const int kSysCpuFieldNumber = 1;
  private:
  const ::CPU& _internal_sys_cpu() const;
  public:
  const ::CPU& sys_cpu() const;
  ::CPU* release_sys_cpu();
  ::CPU* mutable_sys_cpu();
  void set_allocated_sys_cpu(::CPU* sys_cpu);

  // optional .Memory phy_mem = 3;
  bool has_phy_mem() const;
  void clear_phy_mem();
  static const int kPhyMemFieldNumber = 3;
  private:
  const ::Memory& _internal_phy_mem() const;
  public:
  const ::Memory& phy_mem() const;
  ::Memory* release_phy_mem();
  ::Memory* mutable_phy_mem();
  void set_allocated_phy_mem(::Memory* phy_mem);

  // optional .Memory swap_mem = 4;
  bool has_swap_mem() const;
  void clear_swap_mem();
  static const int kSwapMemFieldNumber = 4;
  private:
  const ::Memory& _internal_swap_mem() const;
  public:
  const ::Memory& swap_mem() const;
  ::Memory* release_swap_mem();
  ::Memory* mutable_swap_mem();
  void set_allocated_swap_mem(::Memory* swap_mem);

  // optional .SysProcess tasks = 6;
  bool has_tasks() const;
  void clear_tasks();
  static const int kTasksFieldNumber = 6;
  private:
  const ::SysProcess& _internal_tasks() const;
  public:
  const ::SysProcess& tasks() const;
  ::SysProcess* release_tasks();
  ::SysProcess* mutable_tasks();
  void set_allocated_tasks(::SysProcess* tasks);

  // @@protoc_insertion_point(class_scope:SystemData)
 private:
  void set_has_sys_cpu();
  void clear_has_sys_cpu();
  void set_has_phy_mem();
  void clear_has_phy_mem();
  void set_has_swap_mem();
  void clear_has_swap_mem();
  void set_has_tasks();
  void clear_has_tasks();

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  ::google::protobuf::RepeatedPtrField< ::CPU > cpus_;
  ::google::protobuf::RepeatedPtrField< ::Disk > disks_;
  ::CPU* sys_cpu_;
  ::Memory* phy_mem_;
  ::Memory* swap_mem_;
  ::SysProcess* tasks_;
  friend struct ::protobuf_system_5fdata_2eproto::TableStruct;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// CPU

// optional string name = 1;
inline bool CPU::has_name() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void CPU::set_has_name() {
  _has_bits_[0] |= 0x00000001u;
}
inline void CPU::clear_has_name() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void CPU::clear_name() {
  name_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_name();
}
inline const ::std::string& CPU::name() const {
  // @@protoc_insertion_point(field_get:CPU.name)
  return name_.GetNoArena();
}
inline void CPU::set_name(const ::std::string& value) {
  set_has_name();
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:CPU.name)
}
#if LANG_CXX11
inline void CPU::set_name(::std::string&& value) {
  set_has_name();
  name_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:CPU.name)
}
#endif
inline void CPU::set_name(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  set_has_name();
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:CPU.name)
}
inline void CPU::set_name(const char* value, size_t size) {
  set_has_name();
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:CPU.name)
}
inline ::std::string* CPU::mutable_name() {
  set_has_name();
  // @@protoc_insertion_point(field_mutable:CPU.name)
  return name_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* CPU::release_name() {
  // @@protoc_insertion_point(field_release:CPU.name)
  if (!has_name()) {
    return NULL;
  }
  clear_has_name();
  return name_.ReleaseNonDefaultNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void CPU::set_allocated_name(::std::string* name) {
  if (name != NULL) {
    set_has_name();
  } else {
    clear_has_name();
  }
  name_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), name);
  // @@protoc_insertion_point(field_set_allocated:CPU.name)
}

// optional float usage = 2;
inline bool CPU::has_usage() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void CPU::set_has_usage() {
  _has_bits_[0] |= 0x00000002u;
}
inline void CPU::clear_has_usage() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void CPU::clear_usage() {
  usage_ = 0;
  clear_has_usage();
}
inline float CPU::usage() const {
  // @@protoc_insertion_point(field_get:CPU.usage)
  return usage_;
}
inline void CPU::set_usage(float value) {
  set_has_usage();
  usage_ = value;
  // @@protoc_insertion_point(field_set:CPU.usage)
}

// optional float user_usage = 3;
inline bool CPU::has_user_usage() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void CPU::set_has_user_usage() {
  _has_bits_[0] |= 0x00000004u;
}
inline void CPU::clear_has_user_usage() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void CPU::clear_user_usage() {
  user_usage_ = 0;
  clear_has_user_usage();
}
inline float CPU::user_usage() const {
  // @@protoc_insertion_point(field_get:CPU.user_usage)
  return user_usage_;
}
inline void CPU::set_user_usage(float value) {
  set_has_user_usage();
  user_usage_ = value;
  // @@protoc_insertion_point(field_set:CPU.user_usage)
}

// optional float system_usage = 4;
inline bool CPU::has_system_usage() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void CPU::set_has_system_usage() {
  _has_bits_[0] |= 0x00000008u;
}
inline void CPU::clear_has_system_usage() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void CPU::clear_system_usage() {
  system_usage_ = 0;
  clear_has_system_usage();
}
inline float CPU::system_usage() const {
  // @@protoc_insertion_point(field_get:CPU.system_usage)
  return system_usage_;
}
inline void CPU::set_system_usage(float value) {
  set_has_system_usage();
  system_usage_ = value;
  // @@protoc_insertion_point(field_set:CPU.system_usage)
}

// optional float irq_usage = 5;
inline bool CPU::has_irq_usage() const {
  return (_has_bits_[0] & 0x00000010u) != 0;
}
inline void CPU::set_has_irq_usage() {
  _has_bits_[0] |= 0x00000010u;
}
inline void CPU::clear_has_irq_usage() {
  _has_bits_[0] &= ~0x00000010u;
}
inline void CPU::clear_irq_usage() {
  irq_usage_ = 0;
  clear_has_irq_usage();
}
inline float CPU::irq_usage() const {
  // @@protoc_insertion_point(field_get:CPU.irq_usage)
  return irq_usage_;
}
inline void CPU::set_irq_usage(float value) {
  set_has_irq_usage();
  irq_usage_ = value;
  // @@protoc_insertion_point(field_set:CPU.irq_usage)
}

// optional float softirq_usage = 6;
inline bool CPU::has_softirq_usage() const {
  return (_has_bits_[0] & 0x00000020u) != 0;
}
inline void CPU::set_has_softirq_usage() {
  _has_bits_[0] |= 0x00000020u;
}
inline void CPU::clear_has_softirq_usage() {
  _has_bits_[0] &= ~0x00000020u;
}
inline void CPU::clear_softirq_usage() {
  softirq_usage_ = 0;
  clear_has_softirq_usage();
}
inline float CPU::softirq_usage() const {
  // @@protoc_insertion_point(field_get:CPU.softirq_usage)
  return softirq_usage_;
}
inline void CPU::set_softirq_usage(float value) {
  set_has_softirq_usage();
  softirq_usage_ = value;
  // @@protoc_insertion_point(field_set:CPU.softirq_usage)
}

// optional int32 running_time = 7;
inline bool CPU::has_running_time() const {
  return (_has_bits_[0] & 0x00000040u) != 0;
}
inline void CPU::set_has_running_time() {
  _has_bits_[0] |= 0x00000040u;
}
inline void CPU::clear_has_running_time() {
  _has_bits_[0] &= ~0x00000040u;
}
inline void CPU::clear_running_time() {
  running_time_ = 0;
  clear_has_running_time();
}
inline ::google::protobuf::int32 CPU::running_time() const {
  // @@protoc_insertion_point(field_get:CPU.running_time)
  return running_time_;
}
inline void CPU::set_running_time(::google::protobuf::int32 value) {
  set_has_running_time();
  running_time_ = value;
  // @@protoc_insertion_point(field_set:CPU.running_time)
}

// -------------------------------------------------------------------

// Memory

// optional string name = 1;
inline bool Memory::has_name() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void Memory::set_has_name() {
  _has_bits_[0] |= 0x00000001u;
}
inline void Memory::clear_has_name() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void Memory::clear_name() {
  name_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_name();
}
inline const ::std::string& Memory::name() const {
  // @@protoc_insertion_point(field_get:Memory.name)
  return name_.GetNoArena();
}
inline void Memory::set_name(const ::std::string& value) {
  set_has_name();
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:Memory.name)
}
#if LANG_CXX11
inline void Memory::set_name(::std::string&& value) {
  set_has_name();
  name_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:Memory.name)
}
#endif
inline void Memory::set_name(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  set_has_name();
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:Memory.name)
}
inline void Memory::set_name(const char* value, size_t size) {
  set_has_name();
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:Memory.name)
}
inline ::std::string* Memory::mutable_name() {
  set_has_name();
  // @@protoc_insertion_point(field_mutable:Memory.name)
  return name_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* Memory::release_name() {
  // @@protoc_insertion_point(field_release:Memory.name)
  if (!has_name()) {
    return NULL;
  }
  clear_has_name();
  return name_.ReleaseNonDefaultNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void Memory::set_allocated_name(::std::string* name) {
  if (name != NULL) {
    set_has_name();
  } else {
    clear_has_name();
  }
  name_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), name);
  // @@protoc_insertion_point(field_set_allocated:Memory.name)
}

// optional float total = 2;
inline bool Memory::has_total() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void Memory::set_has_total() {
  _has_bits_[0] |= 0x00000002u;
}
inline void Memory::clear_has_total() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void Memory::clear_total() {
  total_ = 0;
  clear_has_total();
}
inline float Memory::total() const {
  // @@protoc_insertion_point(field_get:Memory.total)
  return total_;
}
inline void Memory::set_total(float value) {
  set_has_total();
  total_ = value;
  // @@protoc_insertion_point(field_set:Memory.total)
}

// optional float used = 3;
inline bool Memory::has_used() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void Memory::set_has_used() {
  _has_bits_[0] |= 0x00000004u;
}
inline void Memory::clear_has_used() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void Memory::clear_used() {
  used_ = 0;
  clear_has_used();
}
inline float Memory::used() const {
  // @@protoc_insertion_point(field_get:Memory.used)
  return used_;
}
inline void Memory::set_used(float value) {
  set_has_used();
  used_ = value;
  // @@protoc_insertion_point(field_set:Memory.used)
}

// optional float free = 4;
inline bool Memory::has_free() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void Memory::set_has_free() {
  _has_bits_[0] |= 0x00000008u;
}
inline void Memory::clear_has_free() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void Memory::clear_free() {
  free_ = 0;
  clear_has_free();
}
inline float Memory::free() const {
  // @@protoc_insertion_point(field_get:Memory.free)
  return free_;
}
inline void Memory::set_free(float value) {
  set_has_free();
  free_ = value;
  // @@protoc_insertion_point(field_set:Memory.free)
}

// optional float shared = 5;
inline bool Memory::has_shared() const {
  return (_has_bits_[0] & 0x00000010u) != 0;
}
inline void Memory::set_has_shared() {
  _has_bits_[0] |= 0x00000010u;
}
inline void Memory::clear_has_shared() {
  _has_bits_[0] &= ~0x00000010u;
}
inline void Memory::clear_shared() {
  shared_ = 0;
  clear_has_shared();
}
inline float Memory::shared() const {
  // @@protoc_insertion_point(field_get:Memory.shared)
  return shared_;
}
inline void Memory::set_shared(float value) {
  set_has_shared();
  shared_ = value;
  // @@protoc_insertion_point(field_set:Memory.shared)
}

// optional float buffer_and_cached = 6;
inline bool Memory::has_buffer_and_cached() const {
  return (_has_bits_[0] & 0x00000020u) != 0;
}
inline void Memory::set_has_buffer_and_cached() {
  _has_bits_[0] |= 0x00000020u;
}
inline void Memory::clear_has_buffer_and_cached() {
  _has_bits_[0] &= ~0x00000020u;
}
inline void Memory::clear_buffer_and_cached() {
  buffer_and_cached_ = 0;
  clear_has_buffer_and_cached();
}
inline float Memory::buffer_and_cached() const {
  // @@protoc_insertion_point(field_get:Memory.buffer_and_cached)
  return buffer_and_cached_;
}
inline void Memory::set_buffer_and_cached(float value) {
  set_has_buffer_and_cached();
  buffer_and_cached_ = value;
  // @@protoc_insertion_point(field_set:Memory.buffer_and_cached)
}

// -------------------------------------------------------------------

// Disk

// optional string file_system = 1;
inline bool Disk::has_file_system() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void Disk::set_has_file_system() {
  _has_bits_[0] |= 0x00000001u;
}
inline void Disk::clear_has_file_system() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void Disk::clear_file_system() {
  file_system_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_file_system();
}
inline const ::std::string& Disk::file_system() const {
  // @@protoc_insertion_point(field_get:Disk.file_system)
  return file_system_.GetNoArena();
}
inline void Disk::set_file_system(const ::std::string& value) {
  set_has_file_system();
  file_system_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:Disk.file_system)
}
#if LANG_CXX11
inline void Disk::set_file_system(::std::string&& value) {
  set_has_file_system();
  file_system_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:Disk.file_system)
}
#endif
inline void Disk::set_file_system(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  set_has_file_system();
  file_system_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:Disk.file_system)
}
inline void Disk::set_file_system(const char* value, size_t size) {
  set_has_file_system();
  file_system_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:Disk.file_system)
}
inline ::std::string* Disk::mutable_file_system() {
  set_has_file_system();
  // @@protoc_insertion_point(field_mutable:Disk.file_system)
  return file_system_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* Disk::release_file_system() {
  // @@protoc_insertion_point(field_release:Disk.file_system)
  if (!has_file_system()) {
    return NULL;
  }
  clear_has_file_system();
  return file_system_.ReleaseNonDefaultNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void Disk::set_allocated_file_system(::std::string* file_system) {
  if (file_system != NULL) {
    set_has_file_system();
  } else {
    clear_has_file_system();
  }
  file_system_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), file_system);
  // @@protoc_insertion_point(field_set_allocated:Disk.file_system)
}

// optional float total = 2;
inline bool Disk::has_total() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void Disk::set_has_total() {
  _has_bits_[0] |= 0x00000004u;
}
inline void Disk::clear_has_total() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void Disk::clear_total() {
  total_ = 0;
  clear_has_total();
}
inline float Disk::total() const {
  // @@protoc_insertion_point(field_get:Disk.total)
  return total_;
}
inline void Disk::set_total(float value) {
  set_has_total();
  total_ = value;
  // @@protoc_insertion_point(field_set:Disk.total)
}

// optional float usage = 3;
inline bool Disk::has_usage() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void Disk::set_has_usage() {
  _has_bits_[0] |= 0x00000008u;
}
inline void Disk::clear_has_usage() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void Disk::clear_usage() {
  usage_ = 0;
  clear_has_usage();
}
inline float Disk::usage() const {
  // @@protoc_insertion_point(field_get:Disk.usage)
  return usage_;
}
inline void Disk::set_usage(float value) {
  set_has_usage();
  usage_ = value;
  // @@protoc_insertion_point(field_set:Disk.usage)
}

// optional string mount = 4;
inline bool Disk::has_mount() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void Disk::set_has_mount() {
  _has_bits_[0] |= 0x00000002u;
}
inline void Disk::clear_has_mount() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void Disk::clear_mount() {
  mount_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_mount();
}
inline const ::std::string& Disk::mount() const {
  // @@protoc_insertion_point(field_get:Disk.mount)
  return mount_.GetNoArena();
}
inline void Disk::set_mount(const ::std::string& value) {
  set_has_mount();
  mount_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:Disk.mount)
}
#if LANG_CXX11
inline void Disk::set_mount(::std::string&& value) {
  set_has_mount();
  mount_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:Disk.mount)
}
#endif
inline void Disk::set_mount(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  set_has_mount();
  mount_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:Disk.mount)
}
inline void Disk::set_mount(const char* value, size_t size) {
  set_has_mount();
  mount_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:Disk.mount)
}
inline ::std::string* Disk::mutable_mount() {
  set_has_mount();
  // @@protoc_insertion_point(field_mutable:Disk.mount)
  return mount_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* Disk::release_mount() {
  // @@protoc_insertion_point(field_release:Disk.mount)
  if (!has_mount()) {
    return NULL;
  }
  clear_has_mount();
  return mount_.ReleaseNonDefaultNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void Disk::set_allocated_mount(::std::string* mount) {
  if (mount != NULL) {
    set_has_mount();
  } else {
    clear_has_mount();
  }
  mount_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), mount);
  // @@protoc_insertion_point(field_set_allocated:Disk.mount)
}

// -------------------------------------------------------------------

// SysProcess

// optional string name = 1;
inline bool SysProcess::has_name() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void SysProcess::set_has_name() {
  _has_bits_[0] |= 0x00000001u;
}
inline void SysProcess::clear_has_name() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void SysProcess::clear_name() {
  name_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_name();
}
inline const ::std::string& SysProcess::name() const {
  // @@protoc_insertion_point(field_get:SysProcess.name)
  return name_.GetNoArena();
}
inline void SysProcess::set_name(const ::std::string& value) {
  set_has_name();
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:SysProcess.name)
}
#if LANG_CXX11
inline void SysProcess::set_name(::std::string&& value) {
  set_has_name();
  name_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:SysProcess.name)
}
#endif
inline void SysProcess::set_name(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  set_has_name();
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:SysProcess.name)
}
inline void SysProcess::set_name(const char* value, size_t size) {
  set_has_name();
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:SysProcess.name)
}
inline ::std::string* SysProcess::mutable_name() {
  set_has_name();
  // @@protoc_insertion_point(field_mutable:SysProcess.name)
  return name_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* SysProcess::release_name() {
  // @@protoc_insertion_point(field_release:SysProcess.name)
  if (!has_name()) {
    return NULL;
  }
  clear_has_name();
  return name_.ReleaseNonDefaultNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void SysProcess::set_allocated_name(::std::string* name) {
  if (name != NULL) {
    set_has_name();
  } else {
    clear_has_name();
  }
  name_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), name);
  // @@protoc_insertion_point(field_set_allocated:SysProcess.name)
}

// optional int32 total = 2;
inline bool SysProcess::has_total() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void SysProcess::set_has_total() {
  _has_bits_[0] |= 0x00000002u;
}
inline void SysProcess::clear_has_total() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void SysProcess::clear_total() {
  total_ = 0;
  clear_has_total();
}
inline ::google::protobuf::int32 SysProcess::total() const {
  // @@protoc_insertion_point(field_get:SysProcess.total)
  return total_;
}
inline void SysProcess::set_total(::google::protobuf::int32 value) {
  set_has_total();
  total_ = value;
  // @@protoc_insertion_point(field_set:SysProcess.total)
}

// optional int32 running = 3;
inline bool SysProcess::has_running() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void SysProcess::set_has_running() {
  _has_bits_[0] |= 0x00000004u;
}
inline void SysProcess::clear_has_running() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void SysProcess::clear_running() {
  running_ = 0;
  clear_has_running();
}
inline ::google::protobuf::int32 SysProcess::running() const {
  // @@protoc_insertion_point(field_get:SysProcess.running)
  return running_;
}
inline void SysProcess::set_running(::google::protobuf::int32 value) {
  set_has_running();
  running_ = value;
  // @@protoc_insertion_point(field_set:SysProcess.running)
}

// optional int32 sleeping = 4;
inline bool SysProcess::has_sleeping() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void SysProcess::set_has_sleeping() {
  _has_bits_[0] |= 0x00000008u;
}
inline void SysProcess::clear_has_sleeping() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void SysProcess::clear_sleeping() {
  sleeping_ = 0;
  clear_has_sleeping();
}
inline ::google::protobuf::int32 SysProcess::sleeping() const {
  // @@protoc_insertion_point(field_get:SysProcess.sleeping)
  return sleeping_;
}
inline void SysProcess::set_sleeping(::google::protobuf::int32 value) {
  set_has_sleeping();
  sleeping_ = value;
  // @@protoc_insertion_point(field_set:SysProcess.sleeping)
}

// optional int32 stopped = 5;
inline bool SysProcess::has_stopped() const {
  return (_has_bits_[0] & 0x00000010u) != 0;
}
inline void SysProcess::set_has_stopped() {
  _has_bits_[0] |= 0x00000010u;
}
inline void SysProcess::clear_has_stopped() {
  _has_bits_[0] &= ~0x00000010u;
}
inline void SysProcess::clear_stopped() {
  stopped_ = 0;
  clear_has_stopped();
}
inline ::google::protobuf::int32 SysProcess::stopped() const {
  // @@protoc_insertion_point(field_get:SysProcess.stopped)
  return stopped_;
}
inline void SysProcess::set_stopped(::google::protobuf::int32 value) {
  set_has_stopped();
  stopped_ = value;
  // @@protoc_insertion_point(field_set:SysProcess.stopped)
}

// optional int32 zombie = 6;
inline bool SysProcess::has_zombie() const {
  return (_has_bits_[0] & 0x00000020u) != 0;
}
inline void SysProcess::set_has_zombie() {
  _has_bits_[0] |= 0x00000020u;
}
inline void SysProcess::clear_has_zombie() {
  _has_bits_[0] &= ~0x00000020u;
}
inline void SysProcess::clear_zombie() {
  zombie_ = 0;
  clear_has_zombie();
}
inline ::google::protobuf::int32 SysProcess::zombie() const {
  // @@protoc_insertion_point(field_get:SysProcess.zombie)
  return zombie_;
}
inline void SysProcess::set_zombie(::google::protobuf::int32 value) {
  set_has_zombie();
  zombie_ = value;
  // @@protoc_insertion_point(field_set:SysProcess.zombie)
}

// -------------------------------------------------------------------

// SystemData

// optional .CPU sys_cpu = 1;
inline bool SystemData::has_sys_cpu() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void SystemData::set_has_sys_cpu() {
  _has_bits_[0] |= 0x00000001u;
}
inline void SystemData::clear_has_sys_cpu() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void SystemData::clear_sys_cpu() {
  if (sys_cpu_ != NULL) sys_cpu_->Clear();
  clear_has_sys_cpu();
}
inline const ::CPU& SystemData::_internal_sys_cpu() const {
  return *sys_cpu_;
}
inline const ::CPU& SystemData::sys_cpu() const {
  const ::CPU* p = sys_cpu_;
  // @@protoc_insertion_point(field_get:SystemData.sys_cpu)
  return p != NULL ? *p : *reinterpret_cast<const ::CPU*>(
      &::_CPU_default_instance_);
}
inline ::CPU* SystemData::release_sys_cpu() {
  // @@protoc_insertion_point(field_release:SystemData.sys_cpu)
  clear_has_sys_cpu();
  ::CPU* temp = sys_cpu_;
  sys_cpu_ = NULL;
  return temp;
}
inline ::CPU* SystemData::mutable_sys_cpu() {
  set_has_sys_cpu();
  if (sys_cpu_ == NULL) {
    auto* p = CreateMaybeMessage<::CPU>(GetArenaNoVirtual());
    sys_cpu_ = p;
  }
  // @@protoc_insertion_point(field_mutable:SystemData.sys_cpu)
  return sys_cpu_;
}
inline void SystemData::set_allocated_sys_cpu(::CPU* sys_cpu) {
  ::google::protobuf::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == NULL) {
    delete sys_cpu_;
  }
  if (sys_cpu) {
    ::google::protobuf::Arena* submessage_arena = NULL;
    if (message_arena != submessage_arena) {
      sys_cpu = ::google::protobuf::internal::GetOwnedMessage(
          message_arena, sys_cpu, submessage_arena);
    }
    set_has_sys_cpu();
  } else {
    clear_has_sys_cpu();
  }
  sys_cpu_ = sys_cpu;
  // @@protoc_insertion_point(field_set_allocated:SystemData.sys_cpu)
}

// repeated .CPU cpus = 2;
inline int SystemData::cpus_size() const {
  return cpus_.size();
}
inline void SystemData::clear_cpus() {
  cpus_.Clear();
}
inline ::CPU* SystemData::mutable_cpus(int index) {
  // @@protoc_insertion_point(field_mutable:SystemData.cpus)
  return cpus_.Mutable(index);
}
inline ::google::protobuf::RepeatedPtrField< ::CPU >*
SystemData::mutable_cpus() {
  // @@protoc_insertion_point(field_mutable_list:SystemData.cpus)
  return &cpus_;
}
inline const ::CPU& SystemData::cpus(int index) const {
  // @@protoc_insertion_point(field_get:SystemData.cpus)
  return cpus_.Get(index);
}
inline ::CPU* SystemData::add_cpus() {
  // @@protoc_insertion_point(field_add:SystemData.cpus)
  return cpus_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::CPU >&
SystemData::cpus() const {
  // @@protoc_insertion_point(field_list:SystemData.cpus)
  return cpus_;
}

// optional .Memory phy_mem = 3;
inline bool SystemData::has_phy_mem() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void SystemData::set_has_phy_mem() {
  _has_bits_[0] |= 0x00000002u;
}
inline void SystemData::clear_has_phy_mem() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void SystemData::clear_phy_mem() {
  if (phy_mem_ != NULL) phy_mem_->Clear();
  clear_has_phy_mem();
}
inline const ::Memory& SystemData::_internal_phy_mem() const {
  return *phy_mem_;
}
inline const ::Memory& SystemData::phy_mem() const {
  const ::Memory* p = phy_mem_;
  // @@protoc_insertion_point(field_get:SystemData.phy_mem)
  return p != NULL ? *p : *reinterpret_cast<const ::Memory*>(
      &::_Memory_default_instance_);
}
inline ::Memory* SystemData::release_phy_mem() {
  // @@protoc_insertion_point(field_release:SystemData.phy_mem)
  clear_has_phy_mem();
  ::Memory* temp = phy_mem_;
  phy_mem_ = NULL;
  return temp;
}
inline ::Memory* SystemData::mutable_phy_mem() {
  set_has_phy_mem();
  if (phy_mem_ == NULL) {
    auto* p = CreateMaybeMessage<::Memory>(GetArenaNoVirtual());
    phy_mem_ = p;
  }
  // @@protoc_insertion_point(field_mutable:SystemData.phy_mem)
  return phy_mem_;
}
inline void SystemData::set_allocated_phy_mem(::Memory* phy_mem) {
  ::google::protobuf::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == NULL) {
    delete phy_mem_;
  }
  if (phy_mem) {
    ::google::protobuf::Arena* submessage_arena = NULL;
    if (message_arena != submessage_arena) {
      phy_mem = ::google::protobuf::internal::GetOwnedMessage(
          message_arena, phy_mem, submessage_arena);
    }
    set_has_phy_mem();
  } else {
    clear_has_phy_mem();
  }
  phy_mem_ = phy_mem;
  // @@protoc_insertion_point(field_set_allocated:SystemData.phy_mem)
}

// optional .Memory swap_mem = 4;
inline bool SystemData::has_swap_mem() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void SystemData::set_has_swap_mem() {
  _has_bits_[0] |= 0x00000004u;
}
inline void SystemData::clear_has_swap_mem() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void SystemData::clear_swap_mem() {
  if (swap_mem_ != NULL) swap_mem_->Clear();
  clear_has_swap_mem();
}
inline const ::Memory& SystemData::_internal_swap_mem() const {
  return *swap_mem_;
}
inline const ::Memory& SystemData::swap_mem() const {
  const ::Memory* p = swap_mem_;
  // @@protoc_insertion_point(field_get:SystemData.swap_mem)
  return p != NULL ? *p : *reinterpret_cast<const ::Memory*>(
      &::_Memory_default_instance_);
}
inline ::Memory* SystemData::release_swap_mem() {
  // @@protoc_insertion_point(field_release:SystemData.swap_mem)
  clear_has_swap_mem();
  ::Memory* temp = swap_mem_;
  swap_mem_ = NULL;
  return temp;
}
inline ::Memory* SystemData::mutable_swap_mem() {
  set_has_swap_mem();
  if (swap_mem_ == NULL) {
    auto* p = CreateMaybeMessage<::Memory>(GetArenaNoVirtual());
    swap_mem_ = p;
  }
  // @@protoc_insertion_point(field_mutable:SystemData.swap_mem)
  return swap_mem_;
}
inline void SystemData::set_allocated_swap_mem(::Memory* swap_mem) {
  ::google::protobuf::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == NULL) {
    delete swap_mem_;
  }
  if (swap_mem) {
    ::google::protobuf::Arena* submessage_arena = NULL;
    if (message_arena != submessage_arena) {
      swap_mem = ::google::protobuf::internal::GetOwnedMessage(
          message_arena, swap_mem, submessage_arena);
    }
    set_has_swap_mem();
  } else {
    clear_has_swap_mem();
  }
  swap_mem_ = swap_mem;
  // @@protoc_insertion_point(field_set_allocated:SystemData.swap_mem)
}

// repeated .Disk disks = 5;
inline int SystemData::disks_size() const {
  return disks_.size();
}
inline void SystemData::clear_disks() {
  disks_.Clear();
}
inline ::Disk* SystemData::mutable_disks(int index) {
  // @@protoc_insertion_point(field_mutable:SystemData.disks)
  return disks_.Mutable(index);
}
inline ::google::protobuf::RepeatedPtrField< ::Disk >*
SystemData::mutable_disks() {
  // @@protoc_insertion_point(field_mutable_list:SystemData.disks)
  return &disks_;
}
inline const ::Disk& SystemData::disks(int index) const {
  // @@protoc_insertion_point(field_get:SystemData.disks)
  return disks_.Get(index);
}
inline ::Disk* SystemData::add_disks() {
  // @@protoc_insertion_point(field_add:SystemData.disks)
  return disks_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::Disk >&
SystemData::disks() const {
  // @@protoc_insertion_point(field_list:SystemData.disks)
  return disks_;
}

// optional .SysProcess tasks = 6;
inline bool SystemData::has_tasks() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void SystemData::set_has_tasks() {
  _has_bits_[0] |= 0x00000008u;
}
inline void SystemData::clear_has_tasks() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void SystemData::clear_tasks() {
  if (tasks_ != NULL) tasks_->Clear();
  clear_has_tasks();
}
inline const ::SysProcess& SystemData::_internal_tasks() const {
  return *tasks_;
}
inline const ::SysProcess& SystemData::tasks() const {
  const ::SysProcess* p = tasks_;
  // @@protoc_insertion_point(field_get:SystemData.tasks)
  return p != NULL ? *p : *reinterpret_cast<const ::SysProcess*>(
      &::_SysProcess_default_instance_);
}
inline ::SysProcess* SystemData::release_tasks() {
  // @@protoc_insertion_point(field_release:SystemData.tasks)
  clear_has_tasks();
  ::SysProcess* temp = tasks_;
  tasks_ = NULL;
  return temp;
}
inline ::SysProcess* SystemData::mutable_tasks() {
  set_has_tasks();
  if (tasks_ == NULL) {
    auto* p = CreateMaybeMessage<::SysProcess>(GetArenaNoVirtual());
    tasks_ = p;
  }
  // @@protoc_insertion_point(field_mutable:SystemData.tasks)
  return tasks_;
}
inline void SystemData::set_allocated_tasks(::SysProcess* tasks) {
  ::google::protobuf::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == NULL) {
    delete tasks_;
  }
  if (tasks) {
    ::google::protobuf::Arena* submessage_arena = NULL;
    if (message_arena != submessage_arena) {
      tasks = ::google::protobuf::internal::GetOwnedMessage(
          message_arena, tasks, submessage_arena);
    }
    set_has_tasks();
  } else {
    clear_has_tasks();
  }
  tasks_ = tasks;
  // @@protoc_insertion_point(field_set_allocated:SystemData.tasks)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)


// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_INCLUDED_system_5fdata_2eproto
